### PR TITLE
Use PaperMC API to fetch jar links for Waterfall and Travertine

### PR DESCRIPTION
**Pull request by INSANEMODE**
based on pull request #339 . the same api can be used to pull waterfall and travertine jars.  
queries the endpoints " https://papermc.io/api/v1/waterfall " and " https://papermc.io/api/v1/travertine " to get all supported protocol versions.

waterfall

travertine)

### CODE REVIEW

**Comment by hexparrot** [comment]
I'm sorry this has gotten an anniversary before it got any attention....

I'm going through all the PRs in this repo but as I'm reviewing this one, it appears that the URIs no longer work, can anybody else confirm this is their experience?  Getting 404 for both.

**Comment by INSANEMODE** [comment]
they both work for me.  

image

image
image


> 
> 
> I'm sorry this has gotten an anniversary before it got any attention....
> 
> I'm going through all the PRs in this repo but as I'm reviewing this one, it appears that the URIs no longer work, can anybody else confirm this is their experience? Getting 404 for both.

**Comment by hexparrot** [comment]
Man, I completely botched this!

**Comment by hexparrot** [comment]
Heya, so there was a rewrite PR for the newest addition of `.profiles.d` to organize profiles into separate files.

This PR was made before that was pulled in, and to get your contributions in seemingly requires the addition of all the removed code, and then the removal of all the added code.

Naturally, it's a bit messy.  Can I ask you a favor to make a new, separate PR that has just Travertine and Waterfall?

I do want you to get attribution, because you did the work.  But if you're also worried you have to learn a new scheme, check out this commit: 9f7ba88159c51d8ff40296ff9f2d1defa4e48b9d

It literally has the changes we want. Feel free to poach those files as a new PR, or any way you feel most comfy.  If you're a bit worn out on it, I can just make the inclusion and it can be done.  LMK.

**Comment by INSANEMODE** [comment]
Yeah, I can take a look at it in a few hours when I get off work

**Pull request closed without merging**
