### PR TITLE
Official mineos

### PR DESCRIPTION
**Pull request by MrBretze**

### CODE REVIEW

**Comment by MrBretze** [comment]
Sorry

**Comment by hexparrot** [comment]
I find it in bad taste to call a forked git the "official" repository.

**Comment by MrBretze** [comment]
Do you want to change this ?

**Comment by hexparrot** [comment]
No, there is no need to change it; administrative changes like this could make it difficult on your end in dealing with updating the git repos, etc. That said, just be mindful that others might by chance see "official mineos" and mistakenly not get the official repo they're expecting.

**Comment by MrBretze** [comment]
Ho yes sorry :/

**Pull request closed without merging**
