### PR TITLE
profile for minecraft bedrock wrapper

### PR DESCRIPTION
**Pull request by tucks**
This is an additional profile for minecraft-bedrock-wrapper which provides support for running the Official Bedrock Server 1.17.10 and likely any future version.

The methodology is documented further at: https://github.com/tucks/mineos-bedrock-wrapper

At present and additional CLI step is required.  If this is a blocker to approval, let's have a quick chat as to implementation and I'll see if I can unblock this appropriately.

### CODE REVIEW

**Comment by flareofghast** [comment]
You could look at using the postdownload attribute to download the official server, check out the cuberite profile.

**Comment by tucks** [comment]
Thanks.  I shall have a look and also deal with the unzip then update the PR.

**Comment by hexparrot** [comment]
> At present and additional CLI step is required. If this is a blocker to approval, let's have a quick chat as to implementation and I'll see if I can unblock this appropriately.

With regard to approval and merging, there would need to be some amount of accompanying instruction.  A few notes:

1) It might be difficult for users who download this as the appliance or otherwise to know where to find the next steps.  Checking your repo was easy enough for me, but I'm also not the target expertise level I hope to aim for.
2) Is the URL for the download instead this? https://github.com/tucks/mineos-bedrock-wrapper/raw/master/download/latest/mineos-bedrock-wrapper-1.0-SNAPSHOT.jar

The one included in your profile I think points to the github landing page for this file: https://github.com/tucks/mineos-bedrock-wrapper/blob/master/download/latest/mineos-bedrock-wrapper-1.0-SNAPSHOT.jar

3) The information required for this extra CLI/outside step might best live either in a) page in the UI or b) in the wiki docs.

Perhaps we can float a moderate visibility banner along the top or bottom that leads to a brand-new "doing assorted minecraft tasks" page. I've never though to do something like that before, but connecting the documentation/instructions somewhere in the webui seems like a fairly obvious user-friendly action.

That or we can make a new wiki page that outlines this in great detail (and then again, link to the wiki--which is now part of the repo--).

Let me know what you think.

**Comment by hexparrot** [comment]
Alternate idea:  minecraft bedrock wrapper and spigot both are presented on their own buttons, but both of them (or maybe profiles, as well) get sucked into an accordion, allowing the potentially-increasing numbers of new buttons to not infringe on prime  monitor real-estate.

**Comment by tucks** [comment]
Heya.  Indeed I'm firmly in the camp of make it easy, make it consumable, else why MineOS - we'd all just roll our own.  Ideally any approach should be so obvious that users should not have to consult docs or wikis to self support.

As I'm new to the project and still finding my feet with dev comms, I posted my main thoughts before getting into a direction at https://discourse.codeemo.com/t/development-direction-and-ethos/4881    

Without wishing to take up any more of your time, I wonder if you might be able to give me a steer via that board post discussion on my alternative proposal.  Otherwise, I'm also good for a dev huddle (zoom/slack/other) at a convenient time to kick the tyres.

FYI, the two urls in for the mineos-bedrock-wrapper-1.0-SNAPSHOT.jar are the same file.

**Comment by hexparrot** [comment]
> FYI, the two urls in for the mineos-bedrock-wrapper-1.0-SNAPSHOT.jar are the same file.

It's referencing the same file, but the non `/raw/` one ends up downloading the HTML file to the profiles directory, since it's a landing page.  The other URL `wget`s properly, as I can tell.

**Comment by tucks** [comment]
@hexparrot am now back from hols and following this up.

**Comment by tucks** [comment]
@hexparrot bumping as I realise you are busy.  I believe this is ready for review.  Please let me know if you require me to do anything else to enable this PR to be merged.

**Comment by hexparrot** [comment]
Heya, I'm sorry for leaving this so long unattended.  I'm looking at it now, but I seem to be running into some issues.

```
info: [WEBUI] Received emit command from 127.0.0.1:user id=bedrock-server-1.17.11.01, time=null, releaseTime=null, type=release, group=minecraft-bedrock, webui_desc=1.17.11.01 Linux x64 release, weight=0, downloaded=false, filename=bedrock-server-1.17.11.01.zip, version=0, release_version=1.17.11.01, url=https://minecraft.azureedge.net/bin-linux/bedrock-server-1.17.11.01.zip, $$hashKey=object:891, command=download
info: [WEBUI] Successfully downloaded https://minecraft.azureedge.net/bin-linux/bedrock-server-1.17.11.01.zip to /var/games/minecraft/profiles/bedrock-server-1.17.11.01/bedrock-server-1.17.11.01.zip
node[2201]: ../src/node_contextify.cc:686:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.
 1: 0xa389b0 node::Abort() [node]
 2: 0xa38a2e  [node]
 3: 0xa2a8c3 node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [node]
 4: 0xc248d5  [node]
 5: 0xc24edf  [node]
 6: 0xc25506 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [node]
 7: 0x1446459  [node]
Aborted
root@mineos:/usr/games/minecraft# 
```

When I attempt to download the bedrock-server, I get this error, and the webui process exits:

```
root@mineos:/var/games/minecraft/profiles/bedrock-server-1.17.10.04# node --version
v14.18.2
```

Not sure if it's directly related, but also MineOS-bedrock-wrapper always comes up empty.  I will attempt to be much more attentive to this PR till we get it resolved, and I appreciate the time and effort you've put in so far to make bedrock happen.

**Comment by tucks** [comment]
Heya.  Strangely.. I have some time in this week so we might be able to smash it out.
No, I've been using 14.x from the docker in https://github.com/tucks/mineos-docker/blob/master/ubuntu-hirsute/Dockerfile (another PR) - though a little older; 14.7.0.
Let me see if I can reproduce the issue you note above with the latest 14.x.

If it's easier to chat, ping me a mail and we can slack/zoom/irc flavour of choice.
I had a big debate as to whether we should allow versioning pinning with bedrock, or if it should always be latest.

But first, let's see if we can get stable.

**Comment by tucks** [comment]
Allo again

So digging a little deeper, I think I have some answers for you.

The traceback post-download is llikely due to an issue with natives or fs-extra (I suspect the former).
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
graceful-fs < 4.x exhibts the ReferenceError: primordials is not defined issue.

The bedrock wrapper appears blank as the software is under the Snapshot option.
I suspect this is more a user expectation issue.  Should I do a formal release?  Currently it is correctly a snapshot.

I do notice that post-download of the bedrock-wrapper, I see the message from the cb() exception:

`info: [WEBUI] Successfully downloaded https://github.com/tucks/mineos-bedrock-wrapper/raw/master/download/latest/mineos-bedrock-wrapper-1.0-SNAPSHOT.jar to /var/games/minecraft/profiles/bedrock-server-wrapper/mineos-bedrock-wrapper-1.0-SNAPSHOT.jar
error: simultaneous download race condition means postdownload hook may not have executed. redownload the profile to ensure proper operation.
`
Is there anything to do here?

**Comment by tucks** [comment]
Update.  It appears that it is not the introduction of natives, but the unzip module.  Using unzipper appeats to resolve the traceback.  However, I now need to add a chmod to the bedrock_server file unpacked by native zip.. which is proving fun as it would seem that the callback isn't firing due to the simultaneous download issue.  Any useful pointers?

**Comment by tucks** [comment]
Hi @hexparrot further to this, a summary so far:

- changing from unzip to unzipper removed the dependency on natives 1.1.6 (which I pinned prior to fix an issue with node_contextify.  This in turn resolves the issue you observes with the primordials.

- I added the methods for using linux unzip to the postdownload of the bedrock.js profile.  I went this route as unzip unpacked all of the zip in memory and then promptly segfaulted.  Unzipper appears to consistently unzip bedrock server correctly, so I am pondering reverting back to the unzip method in server.js, which now appears to work fine

That leaves two final items to resolve, which I am investigating in a different branch.

1) chmod the bedrock_server file post unzip using the postdownload methodology in bedrock.js

I am struggling to validate that postdownload is ever properly called.
The reason we see the 'simultaneous race condition' notice is that SOURCES[args.profile['group']] is undefined and therefore throws a TypeError which is caught by the try except wrapper (server.js:421)
I'll try and get some logging into the profile so I can see what occurs, but effectively I'm hitting .. a 'feature'.

2) Determine whether we should ship a release jar of the bedrock wrapper or if having th user select snapshot is ok.  I wonder if the release/snapshot/other is really required.  There does not appear to be much use of them.  Perhaps the UI could hide unpopulated drop down choices?

**Comment by tucks** [comment]
I have also discovered there is a direct correlation between the profile [group] name and the filename.js in the profile dir.  So, I believe I have a viable path to getting the chmod working.

I'll update the branch again when tested and notify you, then you can advise on the release|snapshot behaviour.

**Comment by tucks** [comment]
I have this working successfully (and easily!)
You now just:
- download the bedrock-server profile version required
- download the bedrock wrapper
- create a new server
- set to unconventional
- copy both profiles to the server
- set the settings as per the following picture
- start the server..... voila

works

I have minor code tidy to do before finalising the PR, I think we'll be done this week.

**Comment by tucks** [comment]
@hexparrot this PR is complete and is good for review again
couple of points, for some reason, sometimes I need to download the bedrock server profile again if the server log shows segfault
the bedrock wrapper is in snapshot, not release

**Comment by hexparrot** [comment]
[08:17:59] mineos-bedrock-wrapper starting Bedrock dedicated server...
[08:17:59] mineos-bedrock-wrapper stopped Bedrock dedicated server...
[08:17:59] sh: 1: ./bedrock_server: not found

Get this error if there isn't an `npm install` after update.  Works flawlessly afterward.

**Comment by tucks** [comment]
Hey @hexparrot 
I've seen your comment about the npm install, but also the merge to master thereafter. I'm surprised that there needs to be a post npm install, since there's no js code post bedrock server deployment. 

Is there anything to do here?

Also what is most useful to pick up? I was going to improve the overall test harness but perhaps there is something else more useful?

**Pull request merged**
