### PR TITLE
refactored profiles for easier reading and modification/ addition

### PR DESCRIPTION
**Pull request by flareofghast**
The profiles.js now reads all .js files from profiles.d, it has some error handling and has been tested running NodeJS manually on webui.js and also from systemctl start mineos.

I used node 10.24.0. Had a few issues with node-gyp rebuild userid. managed to solve it by installing those together.

I also began investigating the new FTB modpacks api, so renamed the old stuff.

### CODE REVIEW

**Comment by hexparrot** [comment]
Oh man, a `profiles.d` organization is a brilliant idea; I love it!

A few things though, as I'm looking at this.  


1. It seems you have a linter that is making a swath of changes that wouldn't be uniform throughout the codebase: we may need to suppress that linting and (perhaps separately) lint the entire thing rather than just one file.
2. .vscode directory needing to exist?

That said, 100% the `.d` model is an improvement warranting inclusion.  I'll see what I can do to make sense of your code changes that aren't lint-related and run the tests, as well.

**Comment by flareofghast** [comment]
1) Sorry about that. I don’t code in vscode or NodeJS for my day job. 
2) no it’s not needed. 

Downside is that someone could include a file in profiles.d that could download a malicious file. There’s nothing I could think of for verification.

**Comment by flareofghast** [comment]
I can try clean it up later.

**Comment by Ahze85283** [comment]
William what if we go ahead and md5 the profiles.d and then store the hash
in the GitHub and have the code check GitHub as a method to secure against
malware or something similar

**Comment by flareofghast** [comment]
What linting settings do you use or linter? I'm relatively ignorant to this.

**Comment by flareofghast** [comment]
OK, so I have looked at trying to conform to other files and I am running into an issue. The issue is I am not able to return the profiles from the profiles.js when required. It works fine when not running as a daemon, but when run as daemon I don't get the profiles returned.... very strange behaviour. If anyone could have a look and tell me what has happened. Here is example code change for profiles.js.

`var logging = require('winston');
var fs = require('fs-extra');
var path = require('path');
var profile_manifests = exports;

var normalizedPath = path.join(__dirname, 'profiles.d');

fs.readdirSync(normalizedPath).forEach(function (file) {
  if (!file.match('template.js')) {
    var loadedProfile = require('./profiles.d/' + file);
    if (loadedProfile.profile !== undefined) {
      var name = file.split('.')[0];
      profile_manifests[name] = loadedProfile.profile;
    }
  }
});`

server.js would require removing the ["profiles_manifest"] after the sources on lines 215 and 370

**Comment by hexparrot** [comment]
I think the primary concern is that there's changes all over, even if it's not centered around your feature update, i.e., almost all the changes to `mineos.js`; some of them might be important, but the majority of the changes to that file are linting changes, which makes the change a bit more noisy.

Again, not that linting is bad, it's just that it can and should be separate from feature additions.

> William what if we go ahead and md5 the profiles.d and then store the hash
in the GitHub and have the code check GitHub as a method to secure against
malware or something similar

I'm not particularly concerned about the possibility of Malware--all the `.d` files will get funneled through git, which means it's been reviewed and it can be trusted (insofar that all the profiles are trusted when cloned to local).

Right now, we're trusting in the Linux permissions that say nobody except the user:group owner can make adjustments to `/usr/games/minecraft` and we can expect similarly from `/profiles.d`.

I will start reviewing this presently.

**Comment by hexparrot** [comment]
> but when run as daemon I don't get the profiles returned

Is this line still present? 

`module.exports = { "profile_manifests" : profile_manifests };`

**Comment by flareofghast** [comment]
Not in the commented attempt. At the start where the variables are I attempt to assign 
var profile_manifests = exports;
Then in the loop I do profile_manifests[name] = ….
It just seems to be when daemonised

**Comment by hexparrot** [comment]
Re-add in that line:

`module.exports = { "profile_manifests" : profile_manifests };`

It seems to resolve the problem for me; it looks like it's workin'.

**Comment by flareofghast** [comment]
importing v2 would be better - newest clone of master with very little touched for profile refactor.

**Pull request closed without merging**
