### PR TITLE
make generate-ssl work on freebsd

### PR DESCRIPTION
**Pull request by josh4trunks**

### CODE REVIEW

**Comment by josh4trunks** [comment]
great, I'm hoping to have a test build of the freenas plugin tonight

**Comment by josh4trunks** [comment]
and this time with SSL enabled by default

**Comment by hexparrot** [comment]
I'm really looking forward to it!  FreeBSD now ranks second in popularity for MineOS deployments and your FreeNAS plugin is truly to credit~

**Comment by hexparrot** [comment]
Did this work with the hashbang kept at `/bin/bash` without the -e?  It turns out that this PR has broken almost all Linux-based uses of the script, where many Ubuntu installs point to `dash` rather than `bash`.

**Comment by josh4trunks** [comment]
freebsd doesn't ship with bash. I think it'd be best we standardize on using /bin/sh as all Unix will have that.

short term
feel free to change it back to bash as the freenas plugin is already built

long term
figure out what is breaking and why in ubuntu's dash implementation of  sh

**Comment by josh4trunks** [comment]
from reading this dash is POSIX compliant, with nothing else.
https://wiki.ubuntu.com/DashAsBinSh

so I'll look into why this script doesn't work and submit a pull request. I'm guessing freebsd's 'sh' just implemented a feature that dash didn't.

**Comment by josh4trunks** [comment]
that wiki should help de-bashify the script. it specifically says == should be replaced with = when using [

**Comment by hexparrot** [comment]
huzzah!  It looks like it might be that easy

**Comment by josh4trunks** [comment]
great, I'll double check the script works on freebsd tonight. but I have a feeling it will

**Comment by hexparrot** [comment]
Alright, things look to be in good order.  Arch and CentOS ship with `/bin/bash -> /bin/bash` and Debian&Turnkey both are running the script fine with their default shell `dash`.

Reverted the hashbang to `/bin/sh` and making the change should take care of FreeBSD and I think we're in good shape.

**Comment by josh4trunks** [comment]
it worked. thanks for the quick work!

**Pull request merged**
