### PR TITLE
redo: add 'Download Archive' infrastructure

### PR DESCRIPTION
**Pull request by hailthemelody**
implementation to follow

### CODE REVIEW

**Comment by hexparrot** [comment]
Are you running into any issues that you need some advice or insight on?

**Comment by hailthemelody** [comment]
Thanks for checking in. I've been researching all about memory-efficient solutions as per your heads up. What are you thoughts on the conversation thread here:

http://stackoverflow.com/questions/6926721/event-loop-for-large-files

**Comment by hexparrot** [comment]
It seems as if choosing an appropriate buffer size could help curb the performance impact.  The smaller the buffer, the slower the transmission, but also the less RAM required--which is key when servers often will have a 24/7 Minecraft server in the background.

I've seen many different NPM deps to accomplish this but it looks like just the built-in fs.createReadStream is as good a solution as any--or better, because you can tune it manually.

**Comment by hailthemelody** [comment]
Thanks! I will look into this.

Of potential note, the OS wrapper (Turnkey Linux) has very slow download speed when using their web GUI (port 12321) - around 240KB/sec on my wired LAN. When using FTP of the same file I get around 6000KB/sec. This slower speed might be by design of the kind of memory management you speak of, so for now I will aim for a metric of around that value until I have a better understanding.

**Comment by hexparrot** [comment]
Is there any progress on this?

**Comment by hailthemelody** [comment]
Hi - nothing beyond the two infrastructure pushes (in my fork) are in place, though I'm resuming efforts in January. My work schedule has gotten in the way of my learning curve with node.js (which is taking me longer to wrap my head around than I anticipated). I understand if you need to move on with another solution in the meantime - sorry!

**Comment by hexparrot** [comment]
No need for apologies--when you should resume this, I will happily lend my efforts to assist you in any way possible and we can re-open this.  This certainly isn't a now-or-never feature, so when it comes to fruition, it'll be very welcome!

**Comment by hailthemelody** [comment]
This is great - thank you. I do have some questions (I didn't want to burden you initially), would it be possible to send them in private message?

**Pull request closed without merging**
