### PR TITLE
updated node-uuid to uuid

### PR DESCRIPTION
**Pull request by flareofghast**

### CODE REVIEW

**Comment by flareofghast** [comment]
Do you want both of these changes? The node-uuid to uuid is because it doesn't operate properly on my dev machine. The gamemodes is because they were wrong. I tried to create separate requests but it just lumped it all together in one.

**Comment by hexparrot** [comment]
Are you sure the node-uuid is an issue?  I've been using node-uuid this entire time without any issue, and uuid is really just a fork (28 ahead, 24 behind).  What doesn't operate properly--do you get errors?  Anything you can help me reproduce?

**Comment by flareofghast** [comment]
It just doesn't detect on my system. It thinks the module is not installed. Have you got the right dependency in package.json? It sorta sucks that our time zones are opposite, it'd be nice to have a decent speed conversation with you.

**Comment by hexparrot** [comment]
Okay so I found the issue at hand.  If you want you can reach me, feel free to try me at my gmail address on gtalk (the one I have listed on git/all the MineOS website stuff).

The problem was on my end.  package.json put a dependency for 'uuid', though my code actually utilized 'node-uuid'.  The reason why the code was working for me this entire time was that at one point, I had npm-installed node-uuid "--global"-ly (so it didn't matter that I kept deleting my repo locally, along with all the repo-nested npms).

Ultimately, both should work for our intents here, but I'm updating package.json to reflect the actual code dependency and got it to work on a fully 100% fresh VM (so no chances of previous actions making it "erroneously" work.

**Comment by hexparrot** [comment]
I've cherry-picked your gamemode commit into master, and the node-uuid/uuid issue was resolved in separate commit I made to master.  This should effectively fix both of the issues you've put in this PR.  Thanks for the first non-me commit to this repo!

**Pull request closed without merging**
