### PR TITLE
Expanded Docker related files

### PR DESCRIPTION
**Pull request by 4o66**
Updated files to better support Docker best practices:
All the values in settings.json that should be configurable as part of the container setup now support setting them via environment variables.

Added an example docker-compose.yml with expanded explanations of all variables.

### CODE REVIEW

**Comment by 4o66** [comment]
After playing with this a bit more, it is clear that I need to make some changes.

Using standard docker volumes is NOT a great way to reduce stress as the permissions lock normal users out, so will update the docker-compose file to a bind mount.

Also, I have been unable to find a way to persist the USER_PASSWORD as an environment variable from inside the container, so that needs some more work.

**Comment by hexparrot** [comment]
Is this closed because it requires more work or is there something about it that inherently doesn't work?

I apologize that I lack the proper savviness to continue to improve this dockerfile.  Should this pull be reopened, but just further evaluated for QA?

**Comment by Ahze85283** [comment]
@hexparrot  It seems to be more of a goal or feature to try to bring the dockerfile more in line with best practices within the community. The reason for its closure from my understanding, was due to needing more work to save the user_password as a EnV.

**Comment by 4o66** [comment]
Closed because it needs more work.

**Pull request closed without merging**
