### PR TITLE
Added french language.

### PR DESCRIPTION
**Pull request by MrBretze**
Ses pas très fini

### CODE REVIEW

**Comment by MrBretze** [comment]
Just a fail sorry :/

**Comment by hexparrot** [comment]
Are the translations no good?

**Comment by MrBretze** [comment]
yes

**Comment by hexparrot** [comment]
Do you want to reopen this PR or make a new one--I'd welcome an FR translation.

**Comment by MrBretze** [comment]
I re-open the pull

**Comment by hexparrot** [comment]
added in #104 just to get the one commit with the good localizations

**Pull request closed without merging**
