### PR TITLE
Automatically stop games on machine shutdown or reboot.

### PR DESCRIPTION
**Pull request by shufflebits**
Hopefully I have made it in the correct style!

### CODE REVIEW

**Comment by hexparrot** [comment]
Is the mineos_shutdown.js not included here?

**Comment by cr08** [comment]
@shufflebits Any updates on this? I think this would be a very crucial addition to MineOS.

**Comment by shufflebits** [comment]
OOPS.
I'll check.

**Comment by shufflebits** [comment]
mineos_shutdown.js is now pushed. At the time I did the original PR, I wasn't familiar with Git.

**Comment by cross** [comment]
Looking at this, this seems like a good thing.  But, I'm not sure.  Why is this needed?  Is this only to prevent problems if the signal to the java processes aren't able to be handled quickly enough?  I'm just wondering if this will affect my servers now, without this change....

**Comment by shufflebits** [comment]
Mineos does not automatically stop the Java processes when the machine is shut down. All that happens is that they get killed (kill -9) by Linux. The world then nearly always gets corrupted.
This script makes systemd wait until all running Miecraft processes have shut down properly, with the world save complete.

**Comment by cross** [comment]
No, on system shutdown UNIX/Linux will kill the java processes with a TERM.  In some cases, if they don't exit, it might also send a -9 (SIGQUIT), but that would be an unusual circumstance.  My servers have not been corrupted on system shutdown, but I'm running on FreeBSD, so might be different.

Have you checked your logs to see how long the servers are taking to shut down?  Mine seem to only take 5-10 seconds, which I would imagine would be well within the time a process manager would wait.

**Comment by jsegaert** [comment]
>  My servers have not been corrupted on system shutdown, but I'm running on FreeBSD, so might be different.

Same here.

**Comment by cr08** [comment]
I'll have to check the logs on mine later. I use the docker image on an Unraid box and any time the docker restarts (either for an upgrade or a nightly backup) it always seems like it stops TOO quick compared to manually shutting down an individual game inside MineOS. So I, too, have worried about incorrect shutdowns. That said I've also never run into any world corruption that I am aware of.

**Comment by shufflebits** [comment]
Aha. I run our server on an old Core2Duo desktop. And the games were usually stuffed with mods, and with huge constructions inside (factories, mines, once an intercontinental railway line). Stopping an game manually took tens of seconds!
So yes, the default process TERM timeout was almost certainly too short.

**Comment by cr08** [comment]
Yeah. I had reviewed my logs and can find no reference to a safe shutdown on my games. My server is set to stop the docker every day at 5am, wait for the system to back up the data, then start it back up.

With that said, would be nice to see this implemented proper. No corruption so far thankfully but would love to just play it safe.

**Review by hexparrot — APPROVED** [review]

**Pull request merged**
