### PR TITLE
Profiles refactor v2

### PR DESCRIPTION
**Pull request by flareofghast**
this is touching as little as possible for the profiles refactor and updated forge.

### CODE REVIEW

**Comment by hexparrot** [comment]
Can you confirm a crash if you attempt downloading Imagicalmine?

**Comment by hexparrot** [comment]
Figured it out; a simultaneous download race condition.  I am providing an answer to this, and I believe I'm going to merge this right after.

**Comment by hexparrot** [comment]
After all this time, I'm still no good with git.  I made a push, which I _guess_ you're able to merge into your own branch `profiles-refactor-v2`, and then it'll update this thread to be your 3+1, which I can squash?

Otherwise, I know I can simply push your 3+ my 1 but then this issue gets closed rather than resolved.  I'll hold off merging until you have a chance to merge so I can test if I'm getting to be a grown-up git user.

**Comment by flareofghast** [comment]
Pull rq from your branch to my profile v2?
I merge then you merge?

**Comment by hexparrot** [comment]
I think so.  Here's the branch I created with your 3 commits as the base, plus my one.  If you merge this over your `profiles-refactor-2`, then I think this #419 will be complete to merge into master.

**Comment by flareofghast** [comment]
I’ll have to do it once I get home in about 7 hours. Work gets in the way.

**Comment by flareofghast** [comment]
If you create a PR from your v2 to my v2 I can merge on my side then it should be updated and you can accept this.

**Comment by hexparrot** [comment]
Boom, I was able to freely push to your PR, of course!

Thanks so much for this rewrite--I really, genuinely love the .d model.  Also super thank you for making me put eyes on this area of the code which I otherwise never figured out how to methodically test.

**Comment by flareofghast** [comment]
Personally I think we could make this project a little more OO. Not sure how much effort you want to expend though, with the ruby version in the works.

**Pull request merged**
