### PR TITLE
Adds color support to the console log

### LINKED ISSUE #129: Color suport for console
Juste add the § in the console for colorise the message because minecraft transale the § to color.

### PR DESCRIPTION
**Pull request by KayoticSully**
closes #129 

Just for completeness on GitHub, this is what this change does.
Image of console log with color

### CODE REVIEW

**Comment by MrBretze** [comment]
Nice !

**Comment by MrBretze** [comment]
That it is possible to make out the command "say §cTest" can also be made in color? (http://puu.sh/kq3fD/339c24aea5.png

**Comment by KayoticSully** [comment]
If what you type in makes the game display color, it will also display it in the console log.  If you find something that in the actual game console is in color, but the web log is not... then that is a bug.  If possible I would appreciate screen-shots of both the actual console log AND the web server log, just to verify that there is an issue.

**Comment by MrBretze** [comment]
I do not know how to say

**Comment by MrBretze** [comment]
I want to do a "/ say §cCOLOR" from the web in minecraft for the "COLOR" appears in red

**Comment by MrBretze** [comment]
Possible to add color on the web? (for this: http://puu.sh/kvOmo/3cad5e19df.png)

**Comment by aliyuchang33** [comment]
Something run with the expression, web shows
图片
`cat` shows
图片
`vim` shows
图片

**Pull request merged**
